version: "3.9"

networks:
  transfer_net:
    driver: bridge

services:
  db:
    image: postgres:18.1
    container_name: postgres_db
    restart: always
    ports:
      - "5022:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${VOLUME_POSTGRES}
    networks:
      - transfer_net
    
  server:
    image: v1dkos/transfer-api-aws:latest
    container_name: transfer_api
    volumes:
      - ${VOLUME_API}
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "5898:8080"
    depends_on:
      - db
    networks:
      - transfer_net

  front:
    image: v1dkos/transfer-react-aws:latest
    container_name: react_front
    depends_on:
      - server
    ports:
      - "3987:80"
    networks:
      - transfer_net